---
  - hosts: localhost
    connection: local
    become: true
    user: root
    gather_facts: yes
    vars:
      # DNS
      route_53_internal: true/false
      route_53_external: true/false
      int_dns_zone: { domain name }
      int_dns_record: { host name }
      int_dns_vpc: { specify vpc }
      int_dns_type: A
      int_dns_ttl: 60
      domain_name: "{{ int_dns_record }}.{{ int_dns_zone }}"
      # Solr_cloud
      config_set_download_external: true/false
      config_set_download_internal: true/false
      solr_config_update: true
      solr_upload: true
      solr_create: false        # Create the collections in the Solr gui to start with
      solr_create_cores: false  # Only use this if you have to create cores explictly
      zookeeper_dns_name_1: zookeeper-1.local
      zookeeper_dns_name_2: zookeeper-2.local
      zookeeper_dns_name_3: zookeeper-3.local
      # Common
      install_dev_tools: false
      update_hostname: true
      update_time_config: true
      hostname: "{{ int_dns_record }}.local"
      timezone: Europe/London
      restart_server: true # Server has to be restarted after changing the timezone config file
    roles:
      - dns
      - solr
      - solr_cloud
      - common
