---

  - include: 0_misc.yml
    when: ( install_packages | bool )

  - include: 1_internal.yml
    when: ( route_53_internal | bool )

  - include: 2_external.yml
    when: ( route_53_external | bool )
